[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
    '@chainlink/contracts-ccip/=lib/ccip/contracts/',
    '@chainlink/contracts/=lib/chainlink/contracts/',
    '@chainlink/local/=lib/chainlink-local/',
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol'
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
